- Corpus (C): Combination of all words of the given dataset. Words can be repeatative
- Vocabulary (V): Unique words of Corpus.
- Document (D): Each records is called as Documents.
- Word (W): Each word of document


### One hot Encoding

- Pros: Easy to intitive and implement
- Cons: Sparcity (it also leads to overfitting), Different dimensionality for each document, need to tain again while changing vocab other than traing vacab, No capturing of semantic meaning


### Bag of words

- Mostly using in Text classification and its effective
- It classify text according to it's frequency of the word, order and sentence of the word doesn't matter
- Pros: Simple and intuitive
- Cons: Sensitive to outliers(words that are rare),Sparcity, handling Out of vocab word (As it ignores new words), Order is ignored of the words, fails to understand semantic meaning. i.e: "This is a good car" and "This is not a good car". since both the sentence having almost same frequency


In [2]:
import numpy as np
import pandas as pd

df = pd.DataFrame({"text": ["people watch man", "people write comment",
                  "man watch people", "people write people"], "output": [1, 1, 0, 1]})
df

text  output
0      people watch man       1
1  people write comment       1
2      man watch people       0
3   people write people       1

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [4]:
bow = cv.fit_transform(df["text"])

In [5]:
# Vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'man': 1, 'write': 4, 'comment': 0}


In [6]:
# print(bow[0])
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 1 0]]
[[1 0 1 0 1]]


In [7]:
cv.transform(["Man watch and write comment of people Man"]).toarray()

array([[1, 2, 1, 1, 1]], dtype=int64)

### Bag of N-Grams(Uni-Grams/Bi-Grams/Tri-Grams....)

- Uni-Gram : Unigram is a single word in the sentence, it can be considered as one feature.
- Bi-gram: It considers two words at once to predict next word.
- Tri-grams: It considers three words at once and so on...
- when we set ngram_range param as (1,1) it;s calels bag of words/ Uni gram. as same as for bi-gram value would be (2,2)
- Prons: Able to identify sementic meaning.
- Cons: As N values get increases it would be more time consuming, Out of vocab problem


In [8]:
cv = CountVectorizer(ngram_range=(2, 2))
cv.fit_transform(df["text"]).toarray()

array([[0, 1, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 1]], dtype=int64)

In [9]:
cv.vocabulary_

{'people watch': 1,
 'watch man': 3,
 'people write': 2,
 'write comment': 5,
 'man watch': 0,
 'watch people': 4,
 'write people': 6}

In [10]:
# if we set ngram_range=(1,2), it would be combination of Uni and Bi gram combined
cv = CountVectorizer(ngram_range=(1, 2))
cv.fit_transform(df["text"]).toarray()
cv.vocabulary_

{'people': 3,
 'watch': 6,
 'man': 1,
 'people watch': 4,
 'watch man': 7,
 'write': 9,
 'comment': 0,
 'people write': 5,
 'write comment': 10,
 'man watch': 2,
 'watch people': 8,
 'write people': 11}

## TF-IDF


- IF: erm Frequency
- IDF: Inverse Dot frequency
- TF = (Number of times term t appears in a document)/(Number of terms in the document)
- IDF = log(N/n), where, N is the number of documents and n is the number of documents a term t has appeared in.
- TF-IDF = TF \* IDF
- In the IF-IDF we assign a weightage to each words using TF and IDF. That words having heighest weitage though it is not frequently used in Corpus, but it is in perticuler document, so for that document that word would have heighest weightage.
- IF also represent probability of that word in perticuler document.
- IDF is logarithmically proportional to inverse number of documents containing this word, which means it will be small when there are many docs. IDF is logarithmically scaled down to prevent extreme values from dominating results. The higher the value, the more important it is for search engine to find this particular word in documents.
- If we have many words and they are not common then their idf will be very small which means these words are less significant than other words.
- If we have many words with high tf and low idf then they are considered as stopwords which will not be useful for searching.


##### Interview Question: Why log is taken while calculating IDF ?

- Suppose there is a word, which having only one use in entire corpus of 10k document. So with our log IDF would be 10k it's big num. and after multiplying it with ID, IDF's weightage would be more. so log is taken. with the log that value would be 4


In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df["text"]).toarray()

array([[0.        , 0.64043405, 0.42389674, 0.64043405, 0.        ],
       [0.72664149, 0.        , 0.37919167, 0.        , 0.5728925 ],
       [0.        , 0.64043405, 0.42389674, 0.64043405, 0.        ],
       [0.        , 0.        , 0.7979221 , 0.        , 0.60276058]])

In [12]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.91629073 1.51082562 1.         1.51082562 1.51082562]
['comment' 'man' 'people' 'watch' 'write']


- Prons: Use full for Information Retirival
- Cons: Sparsity, out of vocab Problem for prediction, dimention, Symentic relation not captured


## Custom Features


- While creating a project we required custom features.
- For an example sentimec analysis project features could be
- Number of +ve word
- Number of -ve word
- Ratio of +ve/-ve words
- Char count
