- Learn PyTorch: https://www.learnpytorch.io/00_pytorch_fundamentals/
- PyTorch Documentation: https://pytorch.org/

1_pytorch_fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Intoduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(5)
print(scalar)
print(scalar.ndim) # Scalar has no dimentions

tensor(5)
0


In [ ]:
# get tensor back as python int
scalar.item()

5

In [ ]:
# Vector
vector = torch.tensor([1, 2, 3, 4, 5])
print(vector)
print(vector.ndim) # Vector has 1 dimension
print(vector.shape)

tensor([1, 2, 3, 4, 5])
1
torch.Size([5])


In [ ]:
# Matrix
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix)
print(matrix.ndim) # Matrix has 2 dimensions
print(matrix.shape)
print(matrix[0])

tensor([[1, 2, 3],
        [4, 5, 6]])
2
torch.Size([2, 3])
tensor([1, 2, 3])


In [ ]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                       [[13, 14, 15],
                        [16, 17, 18]],
                       [[19, 20, 21],
                        [22, 23, 24]]
                       ])
print(tensor)
print(tensor.ndim) # Tensor has 3 dimensions
print(tensor.shape)
print(tensor[0])


tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
3
torch.Size([4, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


### Random tensors

Why rendom tensors ?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of size(3, 4)
random_tensor = torch.rand(3, 4)
print(random_tensor)
print(random_tensor.ndim)

tensor([[0.3332, 0.2202, 0.2393, 0.1196],
        [0.1154, 0.1122, 0.2429, 0.8413],
        [0.5688, 0.2601, 0.7124, 0.4421]])
2


In [ ]:
random_tensor = torch.rand(1, 3, 4)
print(random_tensor)
print(random_tensor.ndim)

tensor([[[0.0934, 0.6704, 0.3735, 0.5580],
         [0.4663, 0.5155, 0.5111, 0.8698],
         [0.7299, 0.2023, 0.5319, 0.5543]]])
3


In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # colour channel (RGB), height/raw, width/clm
print(random_image_size_tensor.ndim)
print(random_image_size_tensor.shape)


3
torch.Size([3, 224, 224])


In [ ]:
# create a random tensor with similar shape to an image tensor
random_tensor = torch.rand(size=(3, 2, 4))
print(random_tensor)

tensor([[[0.8082, 0.4786, 0.1626, 0.3020],
         [0.5927, 0.3696, 0.2188, 0.8253]],

        [[0.8894, 0.1484, 0.1469, 0.9384],
         [0.9893, 0.3620, 0.3644, 0.3714]],

        [[0.3217, 0.2522, 0.0304, 0.3109],
         [0.4621, 0.1693, 0.3564, 0.3451]]])


### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange()
arange_tensor = torch.arange(start=0, end=10, step=2)
print(arange_tensor)


tensor([0, 2, 4, 6, 8])


In [ ]:
# Creating tensors like
five_zeros = torch.zeros_like(input=arange_tensor)
print(five_zeros)

tensor([0, 0, 0, 0, 0])


### Tensor datatypes

**Note**: Tensor datatypes is one of the 3 big error one runs into with PyTorch & deep learning
1. Tensors not right datatype: Tensors having different dtype while operations
2. Tensors not right shape: Tensors having different shape while operations
3. Tensors not on right decive: Tensors stored different device while operations

In [ ]:
# Bydefaul data type is float32, we can change it as required

float_16_tensor = torch.tensor([1, 2, 3],
                               dtype=torch.float16,
                               device=None, # what device is your tensor on. Bydefault device = "cpu"
                               requires_grad=False # Whether or not to track gradients with this tensors operation
                               )
print(float_16_tensor)

tensor([1., 2., 3.], dtype=torch.float16)


In [ ]:
float_64_tensor = float_16_tensor.type(torch.float64)
print(float_64_tensor)

tensor([1., 2., 3.], dtype=torch.float64)


### Getting info from tensors

1. Tensors datatype = to get datatype from tensor, can use `tensor.dtype`
2. Tensor shape = to get shape from tensor, can use `tensor.shape` or `tensor.size()`
3. Tensor device = to get device from tensor, can use `tensor.device`

### Manipulating Tensors (tensor operations)

Tensor operations inclues:
* Addition
* Subtraction
* Multiplication
* Division


In [ ]:
# Create a tensor with random values
tensor = torch.tensor([10, 20, 30])
print(f"Additions: {tensor + 10}")
print(f"Subtractions: {tensor - 2}")
print(f"Multiplication: {tensor * 2}")
print(f"Division: {tensor / 2}")


Additions: tensor([20, 30, 40])
Subtractions: tensor([ 8, 18, 28])
Multiplication: tensor([20, 40, 60])
Division: tensor([ 5., 10., 15.])


In [ ]:
print(f"Additions: {torch.add(tensor , 10)}")
print(f"Subtractions: {torch.sub(tensor , 2)}")
print(f"Multiplication: {torch.mul(tensor , 2)}")
print(f"Division: {torch.div(tensor , 2)}")

Additions: tensor([20, 30, 40])
Subtractions: tensor([ 8, 18, 28])
Multiplication: tensor([20, 40, 60])
Division: tensor([ 5., 10., 15.])


### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. matrix multiplication (dot product)

There are two main rules that performing matrix multiplcation need to satisfy:

1. The **inner dimensions** must match:
- `(3, 2) @ (3, 2 )` won't work
2. The resulting matrix has the shape of the **outer dimensions**
- `(2, 3) @ (3, 2)` => (2, 2)

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Element wise multiplication: {tensor * tensor}")


tensor([10, 20, 30]) * tensor([10, 20, 30])
Element wise multiplication: tensor([100, 400, 900])


In [ ]:
# Matrix multiplication
print(f"Matrix multiplication: {torch.matmul(tensor, tensor)}")

Matrix multiplication: 1400


In [ ]:
# @ symbol can also be used for multiplication
tensor @ tensor

tensor(1400)

### Transpose of the matrix

In [ ]:
tensor_a = torch.tensor([[[1, 2], [3, 4], [5, 6]]])
tensor_a, tensor_a.T

<ipython-input-22-8d919cb71890>:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3614.)
  tensor_a, tensor_a.T


(tensor([[[1, 2],
          [3, 4],
          [5, 6]]]),
 tensor([[[1],
          [3],
          [5]],
 
         [[2],
          [4],
          [6]]]))

## Tensor Aggregation (Min, Max, Mean, sum, etc)

In [ ]:
tensor = torch.arange(0, 100, 10)
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Min
print(f"Minimum value: {torch.min(tensor)}, {tensor.min()}")

Minimum value: 0, 0


In [ ]:
# Max
print(f"Maximum value: {torch.max(tensor)}, {tensor.max()}")

Maximum value: 90, 90


In [ ]:
# Mean

# Below will give an error, bcz torch.arange() generate int62 and for mean required float
# print(f"Mean value: {torch.mean(tensor)}, {tensor.mean()}")

print(torch.mean(tensor.type(torch.float32)))

tensor(45.)


In [ ]:
# Sum
print(f"Sum: {torch.sum(tensor)}, {tensor.sum()}")

Sum: 450, 450


In [ ]:
# Absolute value
print(f"Absolute value: {torch.abs(tensor)}")

Absolute value: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [ ]:
# Square root
print(f"Square root: {torch.sqrt(tensor)}")

Square root: tensor([0.0000, 3.1623, 4.4721, 5.4772, 6.3246, 7.0711, 7.7460, 8.3666, 8.9443,
        9.4868])


## Finding the position in the tensor

In [ ]:
# argmin returns index of target tensor where min element occurs
tensor.argmin()

tensor(0)

In [ ]:
# argmax returns index of target tensor where max element occurs
tensor.argmax()

tensor(9)

## Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshape an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on each other (vstack) or side by side (hstack)
* Squeezing - removes all `1` dimension from a tensor
* UnSqueezing - add a `1` dimension to a tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
tensor_x = torch.arange(1., 10.)
tensor_x, tensor_x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dimension
tensor_x_reshaped = tensor_x.reshape(3, 3)
tensor_x_reshaped, tensor_x_reshaped.shape


(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# Change the view
z = tensor_x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes tensor_x (because a view o a tensor shares the same memory as the original)
z[:, 0] = 5
z, tensor_x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on the each other. dim=0 (vstack) dim=1 (hstack)
x_stacked = torch.stack([tensor_x, tensor_x, tensor_x, tensor_x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# squeeze: remove all single dimenstions from a target tensor
x_reshaped = tensor_x_reshaped.reshape(1,9)
print(f"Original tensor: {x_reshaped}")
print(f"Original tensor size: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nsqueeze tensor: {x_squeezed}")
print(f"squeeze tensor size: {x_squeezed.shape}")

Original tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Original tensor size: torch.Size([1, 9])

squeeze tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
squeeze tensor size: torch.Size([9])


In [ ]:
# unsqueeze: adds a single dimension to a target tensor at a specific dim

print(f"squeeze tensor: {x_squeezed}")
print(f"squeeze tensor size: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0) # dim = 0 is a position, 0 means 0th pos in the size list
print(f"\nunsqueeze tensor: {x_unsqueezed}")
print(f"unsqueeze tensor size: {x_unsqueezed.shape}")


squeeze tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
squeeze tensor size: torch.Size([9])

unsqueeze tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
unsqueeze tensor size: torch.Size([1, 9])


In [ ]:
# Permute: Returns a view of the original tensor input with its dimensions permuted.

x_original = torch.rand(size=(224, 224, 3)) #[height, width, colour channel]
print(f"x Original: {x_original.shape}")

# Permute the original tensor to rearrange the axis order
x_permutted = x_original.permute(2, 0, 1) # shift axis 0->1, 1->2, 2->0
print(f"x permutted: {x_permutted.shape}")

x Original: torch.Size([224, 224, 3])
x permutted: torch.Size([3, 224, 224])


## Indexing (Selecting data from tensor)

Indexing with PyTorch is similar to indexing with Numpy

In [ ]:
x = torch.arange(1, 10).reshape(1, 3 , 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# index on middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Index on most inner bracket
x[0][0][0]

tensor(1)

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
# can also use ":" to select "All" of a target dimention
print(x[:, :, :]) # same as x[0][0][0]
print(x[:, 1, :]) # same as x[0][1][0]
print(x[:, 1, 1]) # same as x[0][1][1]


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[4, 5, 6]])
tensor([5])


In [ ]:
# all element of 0th abd 1st dimensions but only index 1 of 2nd dimention
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# all element of 0th abd 1st dimensions but only index 1 of 1st and 2nd dimentions
x[:, 1, 1]

tensor([5])

In [ ]:
# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor([[3, 6, 9]])


## PyTorch Tensors and Numpy

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [ ]:
# Numpy array to tensot

array = np.arange(1.0, 8.0) # default dtype=float64
tensor = torch.from_numpy(array) # default dtype=float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproductibility (trying to take random out of random)

To reduce the randomness in neural networks any PyTorch comes the concept of **random seed**

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
# create two random tesnors
random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)


tensor([[0.8364, 0.9377, 0.1041, 0.1224],
        [0.8396, 0.3655, 0.6739, 0.2538],
        [0.0142, 0.6646, 0.5451, 0.4410]])
tensor([[0.5963, 0.1605, 0.4898, 0.6348],
        [0.8805, 0.5584, 0.9862, 0.3659],
        [0.3868, 0.5438, 0.2081, 0.4710]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
torch.manual_seed(42)
random_tensor_c = torch.rand(3, 4)

torch.manual_seed(42)
random_tensor_d = torch.rand(3, 4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs

GPU =  CUDA + NVIDIA hardware + PyTorch working behind the scenes

### 1. Getting a GPU

* Google GPU
* Own GPU
* cloud computing - GCP, AWS, Azure


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### 2. Check for GPU access with PyTorch

In [ ]:
# Check for local GPU
torch.cude.is_available()

In [ ]:
# Setup device agnostic code
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [ ]:
# Count
torch.cude.device_count()